### ISSUE TITLE
Not able to install the plugin 

### ISSUE THREAD

**Issue by PrabakarKaruppasamy** [malike/elasticsearch-report-engine#3]
ERROR: `elasticsearch` directory is missing in the plugin zip

Tried to run this command
 `bin/elasticsearch-plugin install https://github.com/malike/elasticsearch-report-engine/archive/master.zip`

Elastic search version:- 5.4.0

**Comment by malike** [comment]
Hello @PrabakarKaruppasamy , 

Use this url instead 
[https://github.com/malike/elasticsearch-report-engine/releases/download/v.1.0.0-RC/st.malike.elasticsearch.report.engine-1.0-RC.zip](https://github.com/malike/elasticsearch-report-engine/releases/download/v.1.0.0-RC/st.malike.elasticsearch.report.engine-1.0-RC.zip). This url [https://github.com/malike/elasticsearch-report-engine/archive/master.zip](https://github.com/malike/elasticsearch-report-engine/archive/master.zip) is the source code repository

**Comment by malike** [comment]
@PrabakarKaruppasamy the plugin was designed for 5.4.1 of Elasticsearch. I'll release one for 5.4 and update the README.

**Comment by PrabakarKaruppasamy** [comment]
@malike  we have tried in Elastic search 5.4.1 facing  _**Exception in thread "main" javax.net.ssl.SSLException: SSL peer shut down incorrectly**_.

**Comment by malike** [comment]
Ok, I didn't experience the same issue. I've decided to release the version of the plugin matching that of Elasticsearch. Hopefully that would guide you. @PrabakarKaruppasamy

**Comment by PrabakarKaruppasamy** [comment]
Thanks for your valuable information.
