### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by bharathphatak** [malike/elasticsearch-report-engine#4]
Hello,

i came across this plugin. I want to try this out. Please can you help me out on how to install this plugin ?

**Comment by malike** [comment]
For which version of Elasticsearch?.

**Comment by bharathphatak** [comment]
ElasticSearch is of version 5.6.4

**Comment by malike** [comment]
It was written and tested with 5.4.0 and 5.4.1, I haven't tested with 5.6.4 of Elasticsearch.

**Comment by bharathphatak** [comment]
My bad. Thanks for the information
