### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by bharathphatak** [malike/elasticsearch-report-engine#5]
Hi,

I am unable to build. olap4 maven link is broken.

mvn clean install
 get's stuck at below step.

Downloading: http://central.maven.org/maven2/org/olap4j/olap4j/0.9.7.309-JS-3/olap4j-0.9.7.309-JS-3.jar

**Comment by malike** [comment]
@bharathphatak ,

It's a transitive dependency 

You can add a maven repository by following the link below 

https://community.jaspersoft.com/questions/826431/failure-find-orgolap4jolap4jjar097309-js-3

**Comment by bharathphatak** [comment]
Thanks :)
